/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockERC20__factory } from "./MockERC20__factory";
export { MultiTokenFaucet__factory } from "./MultiTokenFaucet__factory";
